[package]
name = "local-envx"
version = "0.2.2"
edition = "2024"
publish = true
description = "A local-first CLI for working securely with .env files."
license = "MIT"
repository = "https://github.com/codestorm1875/local-envx"
homepage = "https://github.com/codestorm1875/local-envx"
documentation = "https://github.com/codestorm1875/local-envx#readme"
readme = "README.md"
keywords = ["env", "dotenv", "encryption", "cli", "age"]
categories = ["command-line-utilities", "config"]

[[bin]]
name = "envx"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
thiserror = "1"
time = { version = "0.3", features = ["formatting"] }
ratatui = "0.28"
crossterm = "0.28"
fuzzy-matcher = "0.3"
age = "0.10"
secrecy = "0.8"
rpassword = "7"
dirs = "5"
